name: Promote to PROD

on:
  workflow_dispatch:
    inputs:
      image_ref:
        description: "Full image ref to promote (e.g., myacr.azurecr.io/apps/myapp:sha-abc1234)"
        required: true
      manifest_path:
        description: "PROD manifests path (dir or file)"
        required: true
        default: "dist/aks/overlays/prod"
      namespace:
        description: "Kubernetes namespace (PROD)"
        required: true
        default: "prod"
      deployment_name:
        description: "K8s Deployment name"
        required: true
        default: "myapp"
      container_name:
        description: "Container name inside the Deployment"
        required: true
        default: "api"
      ingress_host:
        description: "Optional Ingress host for smoke test (e.g., app.example.com)"
        required: false
        default: ""

permissions:
  contents: read
  # Optional: use environment gate for approvals
  # Enforce approval in repo Settings → Environments → prod
  # pull-requests: read
  # id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest
    # Optional approval gate:
    # environment: prod

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials (PROD)
        run: |
          az aks get-credentials \
            -g "${{ secrets.AKS_RG_PROD }}" \
            -n "${{ secrets.AKS_CLUSTER_PROD }}" \
            --overwrite-existing

      - name: Ensure namespace exists (PROD)
        run: kubectl create namespace "${{ inputs.namespace }}" --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply manifests (PROD)
        run: kubectl -n "${{ inputs.namespace }}" apply -f "${{ inputs.manifest_path }}"

      - name: Pin Deployment image to the provided image_ref (PROD)
        run: |
          kubectl -n "${{ inputs.namespace }}" set image \
            deployment/${{ inputs.deployment_name }} \
            ${{ inputs.container_name }}="${{ inputs.image_ref }}" \
            --record=true

      - name: Wait for rollout (PROD)
        run: kubectl -n "${{ inputs.namespace }}" rollout status deployment/${{ inputs.deployment_name }} --timeout=300s

      - name: Show pods (PROD)
        run: kubectl -n "${{ inputs.namespace }}" get pods -o wide

      - name: Optional smoke test via ingress (PROD)
        if: ${{ inputs.ingress_host != '' }}
        run: |
          echo "Hitting https://${{ inputs.ingress_host }}/health or /"
          curl -k -sS -m 10 "https://${{ inputs.ingress_host }}/health" || \
          curl -k -sS -m 10 "https://${{ inputs.ingress_host }}/" || \
          (echo "Smoke test failed" && exit 1)